--- #YAML:1.0
name:                Data-Template
version:             0.0004
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              ~
distribution_type:   module
requires:     
    Class::Accessor:               0
    Template:                      0
    Test::More:                    0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
