--- #YAML:1.0
name:                Data-Template
version:             0.0005
abstract:            Generate data structures from templates
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Accessor:               0
    Template:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - A. R. Ferreira <ferreira@cpan.org>
